# General Notes
# -Passing lists directly through GitHub Actions Secrets or Variables causes deployment issues.


# Trigger to run pipeline
on:
  # This event allows you to trigger the workflow manually from the GitHub Actions tab in your repository.
  workflow_dispatch:
    inputs:
      architecture:
        description: 'Is deployment of a Stand-Alone Spoke architecture needed?'
        required: true
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'
      environment:
        description: 'Please select a spoke name: dev or prod'
        required: true
        type: choice
        options:
          - 'dev'
          - 'prod'
        default: 'dev'
      terraform_action:
        description: 'Would you like to run a Terraform apply or destroy command?'
        required: true
        type: choice
        options:
          - 'apply'
          - 'destroy'
        default: 'apply'

# Name of deploy pipeline
name: deploy.sls.stand+alone

# Deploy pipeline jobs
jobs:
  ### Stand-Alone Spoke Model
  Input_Verification:
    name: User Input Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Make scripts executable
        run: chmod +x ./scripts/verify-architecture-selection.sh
      - name: Verify Deployment of Stand-Alone Architecture
        run: ./scripts/verify-architecture-selection.sh ${{ github.event.inputs.architecture }}
  App_Verification:
    name: Verification - ${{ inputs.environment }} environment
    needs: Input_Verification
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=${{ github.event.inputs.environment }}_SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_SECRET_NAME=${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
          echo "CONTAINER_SECRET_NAME=sls-terraform-state-sa-${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "TFVARS_SECRET_NAME=${{ github.event.inputs.environment }}.auto.tfvars" >> $GITHUB_ENV
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Download TFVARS
        run: |
          az storage blob download \
            --file ./terraform/spoke/${{ env.TFVARS_SECRET_NAME }} \
            --container-name ${{ env.CONTAINER_SECRET_NAME }} \
            --account-name ${{ env.STORAGE_ACCOUNT_SECRET_NAME }} \
            --name ${{ env.TFVARS_SECRET_NAME }} \
            --auth-mode login \
            --no-progress > /dev/null
      - name: Terraform - Setup Backend, Initialize, and Plan
        run: |
          cd "terraform/spoke"
          cat >backend.tf <<EOL
          terraform {
            backend "azurerm" {
              subscription_id      = "$ARM_SUBSCRIPTION_ID"
              resource_group_name  = "$ARM_BACKEND_RESOURCE_GROUP_NAME"
              storage_account_name = "$ARM_BACKEND_STORAGE_ACCOUNT_NAME"
              container_name       = "$ARM_CONTAINER_NAME"
              key                  = "${{ github.event.inputs.environment }}.tfstate"
              client_id            = "$ARM_CLIENT_ID"
              client_secret        = "$ARM_CLIENT_SECRET"
              tenant_id            = "$ARM_TENANT_ID"
              use_azuread_auth     = true
            }
          }
          EOL
          terraform init
          if [ ${{ github.event.inputs.terraform_action }} = "apply" ]; then
            terraform plan \
            -var="SubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" \
            -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" \
            -var="AdminPassword=${{ secrets.VM_ADMIN_CREDENTIALS }}" \
            -var="EnvName=sa-${{ github.event.inputs.environment }}"
          elif [ ${{ github.event.inputs.terraform_action }} = "destroy" ]; then
            terraform plan -destroy \
            -var="SubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" \
            -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" \
            -var="AdminPassword=${{ secrets.VM_ADMIN_CREDENTIALS }}" \
            -var="EnvName=sa-${{ github.event.inputs.environment }}"
          else
              echo "Please input either an apply or destroy command (case sensitive)."
              exit 1
          fi
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.ARM_BACKEND_RESOURCE_GROUP_NAME }} 
          ARM_BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}
          ARM_CONTAINER_NAME: "sls-terraform-state-sa-${{ github.event.inputs.environment }}"
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  App_Deployment:
    name: Deployment - ${{ inputs.environment }} environment
    needs: App_Verification
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=${{ github.event.inputs.environment }}_SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_SECRET_NAME=${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
          echo "CONTAINER_SECRET_NAME=sls-terraform-state-sa-${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "TFVARS_SECRET_NAME=${{ github.event.inputs.environment }}.auto.tfvars" >> $GITHUB_ENV
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Download TFVARS
        run: |
          az storage blob download \
            --file ./terraform/spoke/${{ env.TFVARS_SECRET_NAME }} \
            --container-name ${{ env.CONTAINER_SECRET_NAME }} \
            --account-name ${{ env.STORAGE_ACCOUNT_SECRET_NAME }} \
            --name ${{ env.TFVARS_SECRET_NAME }} \
            --auth-mode login \
            --no-progress > /dev/null
      - name: Terraform - Setup Backend and Apply
        run: |
          cd "terraform/spoke"
          cat >backend.tf <<EOL
          terraform {
            backend "azurerm" {
              subscription_id      = "$ARM_SUBSCRIPTION_ID"
              resource_group_name  = "$ARM_BACKEND_RESOURCE_GROUP_NAME"
              storage_account_name = "$ARM_BACKEND_STORAGE_ACCOUNT_NAME"
              container_name       = "$ARM_CONTAINER_NAME"
              key                  = "${{ github.event.inputs.environment }}.tfstate"
              client_id            = "$ARM_CLIENT_ID"
              client_secret        = "$ARM_CLIENT_SECRET"
              tenant_id            = "$ARM_TENANT_ID"
              use_azuread_auth     = true
            }
          }
          EOL
          terraform init
          terraform ${{ github.event.inputs.terraform_action }} -auto-approve \
          -var="SubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" \
          -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" \
          -var="AdminPassword=${{ secrets.VM_ADMIN_CREDENTIALS }}" \
          -var="EnvName=sa-${{ github.event.inputs.environment }}"
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.ARM_BACKEND_RESOURCE_GROUP_NAME }} 
          ARM_BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}
          ARM_CONTAINER_NAME: "sls-terraform-state-sa-${{ github.event.inputs.environment }}"
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}