# Trigger to run pipeline
on:
  # This event allows you to trigger the workflow manually from the GitHub Actions tab in your repository.
  workflow_dispatch:
    inputs:
      hub:
        description: 'Is a hub & spoke deployment needed?'
        required: true
        default: 'true'
      environment:
        description: 'What is the name of the spoke environment to deploy (for example: dev, test, and prod)?'
        required: true
        default: 'dev'
      terraform_action:
        description: 'Would you like to run a Terraform apply or destroy command?'
        required: true
        default: 'apply'
      # spoke_model: # Aimed for Release 24.07
      #   description: 'Is the spoke cloud service model IaaS or PaaS?'
      #   required: true
      #   default: 'IaaS'

# Name of deploy pipeline
name: deploy.beta.hub+spoke

# Deploy pipeline jobs
jobs:
  Hub_Verification:
    if: ${{ github.event.inputs.hub == 'true' }}
    name: Hub Pre-Verification
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_HUB" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=HUB_SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "CONTAINER_NAME_SECRET_NAME=HUB_CONTAINER_NAME" >> $GITHUB_ENV
      - name: Login to Azure - Hub
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Terraform Hub - Setup Backend, Initialize, and Plan
        run: |
          cd "terraform/hub"
          cat >backend.tf <<EOL
          terraform {
            backend "azurerm" {
              subscription_id      = "$ARM_SUBSCRIPTION_ID"
              resource_group_name  = "$ARM_BACKEND_RESOURCE_GROUP_NAME"
              storage_account_name = "$ARM_BACKEND_STORAGE_ACCOUNT_NAME"
              container_name       = "$ARM_CONTAINER_NAME"
              key                  = "hub.tfstate"
            }
          }
          EOL
          terraform init
          terraform_action=$(echo "${{ github.event.inputs.terraform_action }}" | tr '[:upper:]' '[:lower:]')
          if [ "$terraform_action" = "apply" ]; then
              terraform plan -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}"
          elif [ "$terraform_action" = "destroy" ]; then
              terraform plan -destroy -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}"
          else
              echo "Please input either an apply or destroy command (case sensitive)."
              exit 1
          fi
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.ARM_BACKEND_RESOURCE_GROUP_NAME }} 
          ARM_BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          ARM_CONTAINER_NAME: ${{ secrets.HUB_CONTAINER_NAME }}

  Hub_Deployment:
    if: ${{ github.event.inputs.hub == 'true' }}
    name: Hub Deployment
    needs: Hub_Verification
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_HUB" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=HUB_SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "CONTAINER_NAME_SECRET_NAME=HUB_CONTAINER_NAME" >> $GITHUB_ENV
      - name: Login to Azure - Hub
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Terraform Hub - Setup Backend and Apply
        run: |
          cd "terraform/hub"
          cat >backend.tf <<EOL
          terraform {
            backend "azurerm" {
              subscription_id      = "$ARM_SUBSCRIPTION_ID"
              resource_group_name  = "$ARM_BACKEND_RESOURCE_GROUP_NAME"
              storage_account_name = "$ARM_BACKEND_STORAGE_ACCOUNT_NAME"
              container_name       = "$ARM_CONTAINER_NAME"
              key                  = "hub.tfstate"
            }
          }
          EOL
          terraform init
          terraform_action=$(echo "${{ github.event.inputs.terraform_action }}" | tr '[:upper:]' '[:lower:]')
          terraform "$terraform_action" -auto-approve -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}"
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.ARM_BACKEND_RESOURCE_GROUP_NAME }} 
          ARM_BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          ARM_CONTAINER_NAME: ${{ secrets.HUB_CONTAINER_NAME }}
      - name: Set output
        id: deployment_output
        run: echo "::set-output name=run::true"

### Spoke with Hub
  App_Verification:
    if: ${{ github.event.inputs.hub == 'true' }}
    name: Pre-Verification - ${{ inputs.environment }} environment
    needs: Hub_Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=${{ github.event.inputs.environment }}_SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "CONTAINER_NAME_SECRET_NAME=${{ github.event.inputs.environment }}_CONTAINER_NAME" >> $GITHUB_ENV
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Terraform - Setup Backend, Initialize, and Plan
        run: |
          cd "terraform/spoke"
          cat >backend.tf <<EOL
          terraform {
            backend "azurerm" {
              subscription_id      = "$ARM_SUBSCRIPTION_ID"
              resource_group_name  = "$ARM_BACKEND_RESOURCE_GROUP_NAME"
              storage_account_name = "$ARM_BACKEND_STORAGE_ACCOUNT_NAME"
              container_name       = "$ARM_CONTAINER_NAME"
              key                  = "${{ github.event.inputs.environment }}.tfstate"
            }
          }
          EOL
          terraform init
          terraform_action=$(echo "${{ github.event.inputs.terraform_action }}" | tr '[:upper:]' '[:lower:]')
          if [ "$terraform_action" = "apply" ]; then
              terraform plan -var="SubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" -var="AdminPassword=${{ secrets.VM_ADMIN_CREDENTIALS }}" -var="HubEnabled=true" -var="EnvName=hs-${{ github.event.inputs.environment }}"
          elif [ "$terraform_action" = "destroy" ]; then
              terraform plan -destroy -var="SubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" -var="AdminPassword=${{ secrets.VM_ADMIN_CREDENTIALS }}" -var="HubEnabled=false" -var="EnvName=hs-${{ github.event.inputs.environment }}"
          else
              echo "Please input either an apply or destroy command (case sensitive)."
              exit 1
          fi
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.ARM_BACKEND_RESOURCE_GROUP_NAME }} 
          ARM_BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          ARM_CONTAINER_NAME: "sls-terraform-state-${{ github.event.inputs.environment }}"

  App_Deployment:
    if: ${{ github.event.inputs.hub == 'true' }}
    name: Deployment - ${{ inputs.environment }} environment
    needs: App_Verification
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=${{ github.event.inputs.environment }}_SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "CONTAINER_NAME_SECRET_NAME=${{ github.event.inputs.environment }}_CONTAINER_NAME" >> $GITHUB_ENV
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Terraform - Setup Backend and Apply
        run: |
          cd "terraform/spoke"
          cat >backend.tf <<EOL
          terraform {
            backend "azurerm" {
              subscription_id      = "$ARM_SUBSCRIPTION_ID"
              resource_group_name  = "$ARM_BACKEND_RESOURCE_GROUP_NAME"
              storage_account_name = "$ARM_BACKEND_STORAGE_ACCOUNT_NAME"
              container_name       = "$ARM_CONTAINER_NAME"
              key                  = "${{ github.event.inputs.environment }}.tfstate"
            }
          }
          EOL
          terraform init
          terraform_action=$(echo "${{ github.event.inputs.terraform_action }}" | tr '[:upper:]' '[:lower:]')
          if [ "$terraform_action" = "apply" ]; then
              terraform apply -auto-approve -var="SubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" -var="AdminPassword=${{ secrets.VM_ADMIN_CREDENTIALS }}" -var="HubEnabled=true" -var="EnvName=hs-${{ github.event.inputs.environment }}"
          elif [ "$terraform_action" = "destroy" ]; then
              terraform destroy -auto-approve -var="SubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" -var="AdminPassword=${{ secrets.VM_ADMIN_CREDENTIALS }}" -var="HubEnabled=false" -var="EnvName=hs-${{ github.event.inputs.environment }}"
          else
              echo "Please input either an apply or destroy command (case sensitive)."
              exit 1
          fi         
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.ARM_BACKEND_RESOURCE_GROUP_NAME }} 
          ARM_BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          ARM_CONTAINER_NAME: "sls-terraform-state-${{ github.event.inputs.environment }}"

