# Trigger to run pipeline
on:
  # This event allows you to trigger the workflow manually from the GitHub Actions tab in your repository.
  workflow_dispatch:
    inputs:
      environment:
        description: 'What is the name of environment to deploy?'
        required: true
        default: 'dev'
      hub:
        description: 'Is a hub deployment needed?'
        required: true
        default: 'true'
# Name of deploy pipeline
name: deploy.beta.1

# Deploy pipeline jobs
jobs:
  Hub_Verification:
    if: ${{ github.event.inputs.hub == 'true' }}
    name: Hub Pre-Verification
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_HUB" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=HUB_SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "CONTAINER_NAME_SECRET_NAME=HUB_CONTAINER_NAME" >> $GITHUB_ENV
      - name: Login to Azure - Hub
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Terraform Hub - Setup Backend, Initialize, and Plan
        run: |
          cd "terraform/hub"
          cat >backend.tf <<EOL
          terraform {
            backend "azurerm" {
              subscription_id      = "${{ secrets.ARM_SUBSCRIPTION_ID }}"
              resource_group_name  = "${{ secrets.ARM_BACKEND_RESOURCE_GROUP_NAME }}"
              storage_account_name = "${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}"
              container_name       = "${{ secrets[env.CONTAINER_NAME_SECRET_NAME] }}"
              key                  = "hub.tfstate"
            }
          }
          EOL
          terraform init
          terraform plan -var="HubSubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}"

  Hub_Deployment:
    if: ${{ github.event.inputs.hub == 'true' }}
    name: Hub Deployment
    needs: Hub_Verification
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_HUB" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=HUB_SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "CONTAINER_NAME_SECRET_NAME=HUB_CONTAINER_NAME" >> $GITHUB_ENV
      - name: Login to Azure - Hub
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Terraform Hub - Setup Backend and Apply
        run: |
          cd "terraform/hub"
          cat >backend.tf <<EOL
          terraform {
            backend "azurerm" {
              subscription_id      = "${{ secrets.ARM_SUBSCRIPTION_ID }}"
              resource_group_name  = "${{ secrets.ARM_BACKEND_RESOURCE_GROUP_NAME }}"
              storage_account_name = "${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}"
              container_name       = "${{ secrets[env.CONTAINER_NAME_SECRET_NAME] }}"
              key                  = "hub.tfstate"
            }
          }
          EOL
          terraform init
          terraform apply -auto-approve -var="HubSubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}"
      - name: Set output
        id: deployment_output
        run: echo "::set-output name=run::true"

  App_Verification:
    if: ${{ needs.Hub_Deployment.outputs.run == 'true' || github.event.inputs.hub != 'true' }}
    name: Pre-Verification - ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=${{ github.event.inputs.environment }}_SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "CONTAINER_NAME_SECRET_NAME=${{ github.event.inputs.environment }}_CONTAINER_NAME" >> $GITHUB_ENV
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Terraform - Setup Backend, Initialize, and Plan
        run: |
          cd "terraform/${{ github.event.inputs.environment }}"
          cat >backend.tf <<EOL
          terraform {
            backend "azurerm" {
              subscription_id      = "${{ secrets.ARM_SUBSCRIPTION_ID }}"
              resource_group_name  = "${{ secrets.ARM_BACKEND_RESOURCE_GROUP_NAME }}"
              storage_account_name = "${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}"
              container_name       = "${{ secrets[env.CONTAINER_NAME_SECRET_NAME] }}"
              key                  = "${{ github.event.inputs.environment }}.tfstate"
            }
          }
          EOL
          cat backend.tf
          terraform init
          terraform plan -var="${{ github.event.inputs.environment }}SubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" -var="AdminPassword=${{ secrets.VM_ADMIN_CREDENTIALS }}" -var="HubEnabled=${{ github.event.inputs.hub }}"

  App_Deployment:
    name: Deployment - ${{ inputs.environment }}
    needs: App_Verification
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=${{ github.event.inputs.environment }}_SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "CONTAINER_NAME_SECRET_NAME=${{ github.event.inputs.environment }}_CONTAINER_NAME" >> $GITHUB_ENV
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Terraform - Setup Backend and Apply
        run: |
          cd "terraform/${{ github.event.inputs.environment }}"
          cat >backend.tf <<EOL
          terraform {
            backend "azurerm" {
              subscription_id      = "${{ secrets.ARM_SUBSCRIPTION_ID }}"
              resource_group_name  = "${{ secrets.ARM_BACKEND_RESOURCE_GROUP_NAME }}"
              storage_account_name = "${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}"
              container_name       = "${{ secrets[env.CONTAINER_NAME_SECRET_NAME] }}"
              key                  = "${{ github.event.inputs.environment }}.tfstate"
            }
          }
          EOL
          terraform init
          terraform apply -auto-approve -var="${{ github.event.inputs.environment }}SubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" -var="AdminPassword=${{ secrets.VM_ADMIN_CREDENTIALS }}" -var="HubEnabled=${{ github.event.inputs.hub }}"

