# General Notes
# -Passing lists directly through GitHub Actions Secrets or Variables causes deployment issues.


# Trigger to run pipeline
on:
  # This event allows you to trigger the workflow manually from the GitHub Actions tab in your repository.
  workflow_dispatch:
    inputs:
      hub:
        description: 'Is a hub & spoke deployment needed?'
        required: true
        default: 'true'
      environment:
        description: 'Please select a spoke name: dev, test, or prod (case sensitive)?'
        required: true
        default: 'dev'
      terraform_action:
        description: 'Would you like to run a Terraform apply or destroy command (case sensitive)?'
        required: true
        default: 'apply'
      # spoke_model: # Aimed for Release 24.07 or later
      #   description: 'Is the spoke cloud service model IaaS or PaaS?'
      #   required: true
      #   default: 'IaaS'

# Name of deploy pipeline
name: deploy.sls.hub+spoke

# Deploy pipeline jobs
jobs:
  ### Hub & Spoke Model
  Input_Verification:
    name: User Input Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Make scripts executable
        run: chmod +x ./scripts/verify-environment.sh ./scripts/verify-terraform-action.sh
      - name: Verify Environment Name is dev, test, or prod
        run: ./scripts/verify-environment.sh ${{ github.event.inputs.environment }}
      - name: Verify Terraform Action is apply or destroy
        run: ./scripts/verify-terraform-action.sh ${{ github.event.inputs.terraform_action }}
  Hub_Verification:
    if: ${{ github.event.inputs.hub == 'true' }}
    name: Hub Pre-Verification
    needs: Input_Verification 
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_HUB" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=${{ secrets.HUB_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_SECRET_NAME=${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
          echo "CONTAINER_SECRET_NAME=${{ secrets.HUB_CONTAINER_NAME }}" >> $GITHUB_ENV
      - name: Login to Azure - Hub
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Download TFVARS
        run: |
          az storage blob download \
            --file ./terraform/hub/hub.auto.tfvars \
            --container-name ${{ env.CONTAINER_SECRET_NAME }} \
            --account-name ${{ env.STORAGE_ACCOUNT_SECRET_NAME }} \
            --name hub.auto.tfvars \
            --auth-mode login \
            --no-progress > /dev/null
      - name: Terraform Hub - Setup Backend, Initialize, and Plan
        run: |
          cd "terraform/hub"
          cat >backend.tf <<EOL
          terraform {
            backend "azurerm" {
              subscription_id      = "$ARM_SUBSCRIPTION_ID"
              resource_group_name  = "$ARM_BACKEND_RESOURCE_GROUP_NAME"
              storage_account_name = "$ARM_BACKEND_STORAGE_ACCOUNT_NAME"
              container_name       = "$ARM_CONTAINER_NAME"
              key                  = "hub.tfstate"
              client_id            = "$ARM_CLIENT_ID"
              client_secret        = "$ARM_CLIENT_SECRET"
              tenant_id            = "$ARM_TENANT_ID"
              use_azuread_auth     = true
            }
          }
          EOL

          terraform init
          if [ ${{ github.event.inputs.terraform_action }} = "apply" ]; then
              terraform plan \
                -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" \
                -var="VnetAddressSpace=${HUB_VNET_CIDR}" \
                -var="BastionSubnetPrefix=${BASTION_SUBNET_CIDR}" \
                -var="GatewaySubnetPrefix=${GATEWAY_SUBNET_CIDR}" \
                -var="MgmtSubnetPrefix=${MGMT_SUBNET_CIDR}"
          elif [ ${{ github.event.inputs.terraform_action }} = "destroy" ]; then
              terraform plan -destroy \
                -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" \
                -var="VnetAddressSpace=${HUB_VNET_CIDR}" \
                -var="BastionSubnetPrefix=${BASTION_SUBNET_CIDR}" \
                -var="GatewaySubnetPrefix=${GATEWAY_SUBNET_CIDR}" \
                -var="MgmtSubnetPrefix=${MGMT_SUBNET_CIDR}"
          else
              echo "Please input either an apply or destroy command (case sensitive)."
              exit 1
          fi
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.ARM_BACKEND_RESOURCE_GROUP_NAME }} 
          ARM_BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}
          ARM_CONTAINER_NAME: ${{ secrets.HUB_CONTAINER_NAME }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          HUB_VNET_CIDR: ${{ secrets.HUB_VNET_CIDR }}
          BASTION_SUBNET_CIDR: ${{ secrets.BASTION_SUBNET_CIDR }}
          GATEWAY_SUBNET_CIDR: ${{ secrets.GATEWAY_SUBNET_CIDR }}
          MGMT_SUBNET_CIDR: ${{ secrets.MGMT_SUBNET_CIDR }} 

  Hub_Deployment:
    if: ${{ github.event.inputs.hub == 'true' }}
    name: Hub Deployment
    needs: Hub_Verification
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_HUB" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=${{ secrets.HUB_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_SECRET_NAME=${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
          echo "CONTAINER_SECRET_NAME=${{ secrets.HUB_CONTAINER_NAME }}" >> $GITHUB_ENV
      - name: Login to Azure - Hub
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Download TFVARS
        run: |
          az storage blob download \
            --file ./terraform/hub/hub.auto.tfvars \
            --container-name ${{ env.CONTAINER_SECRET_NAME }} \
            --account-name ${{ env.STORAGE_ACCOUNT_SECRET_NAME }} \
            --name hub.auto.tfvars \
            --auth-mode login \
            --no-progress > /dev/null
      - name: Terraform Hub - Setup Backend and Apply
        run: |
          cd "terraform/hub"
          cat >backend.tf <<EOL
          terraform {
            backend "azurerm" {
              subscription_id      = "$ARM_SUBSCRIPTION_ID"
              resource_group_name  = "$ARM_BACKEND_RESOURCE_GROUP_NAME"
              storage_account_name = "$ARM_BACKEND_STORAGE_ACCOUNT_NAME"
              container_name       = "$ARM_CONTAINER_NAME"
              key                  = "hub.tfstate"
              client_id            = "$ARM_CLIENT_ID"
              client_secret        = "$ARM_CLIENT_SECRET"
              tenant_id            = "$ARM_TENANT_ID"
              use_azuread_auth     = true
            }
          }
          EOL
          terraform init
          terraform ${{ github.event.inputs.terraform_action }} -auto-approve \
            -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" \
            -var="VnetAddressSpace=${HUB_VNET_CIDR}" \
            -var="BastionSubnetPrefix=${BASTION_SUBNET_CIDR}" \
            -var="GatewaySubnetPrefix=${GATEWAY_SUBNET_CIDR}" \
            -var="MgmtSubnetPrefix=${MGMT_SUBNET_CIDR}"
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.ARM_BACKEND_RESOURCE_GROUP_NAME }} 
          ARM_BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}
          ARM_CONTAINER_NAME: ${{ secrets.HUB_CONTAINER_NAME }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          HUB_VNET_CIDR: ${{ secrets.HUB_VNET_CIDR }}
          BASTION_SUBNET_CIDR: ${{ secrets.BASTION_SUBNET_CIDR }}
          GATEWAY_SUBNET_CIDR: ${{ secrets.GATEWAY_SUBNET_CIDR }}
          MGMT_SUBNET_CIDR: ${{ secrets.MGMT_SUBNET_CIDR }} 
      - name: Set output
        id: deployment_output
        run: echo "::set-output name=run::true"

### Spoke with Hub
  App_Verification:
    if: ${{ github.event.inputs.hub == 'true' }}
    name: Pre-Verification - ${{ inputs.environment }} environment
    needs: Hub_Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=${{ github.event.inputs.environment }}_SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_SECRET_NAME=${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
          echo "CONTAINER_SECRET_NAME=sls-terraform-state-${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "TFVARS_SECRET_NAME=${{ github.event.inputs.environment }}.auto.tfvars" >> $GITHUB_ENV
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Download TFVARS
        run: |
          az storage blob download \
            --file ./terraform/spoke/${{ env.TFVARS_SECRET_NAME }} \
            --container-name ${{ env.CONTAINER_SECRET_NAME }} \
            --account-name ${{ env.STORAGE_ACCOUNT_SECRET_NAME }} \
            --name ${{ env.TFVARS_SECRET_NAME }} \
            --auth-mode login \
            --no-progress > /dev/null
      - name: Terraform - Setup Backend, Initialize, and Plan
        run: |
          cd "terraform/spoke"
          cat >backend.tf <<EOL
          terraform {
            backend "azurerm" {
              subscription_id      = "$ARM_SUBSCRIPTION_ID"
              resource_group_name  = "$ARM_BACKEND_RESOURCE_GROUP_NAME"
              storage_account_name = "$ARM_BACKEND_STORAGE_ACCOUNT_NAME"
              container_name       = "$ARM_CONTAINER_NAME"
              key                  = "${{ github.event.inputs.environment }}.tfstate"
              client_id            = "$ARM_CLIENT_ID"
              client_secret        = "$ARM_CLIENT_SECRET"
              tenant_id            = "$ARM_TENANT_ID"
              use_azuread_auth     = true
            }
          }
          EOL
          terraform init
          if [ ${{ github.event.inputs.terraform_action }} = "apply" ]; then
            terraform plan \
            -var="SubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" \
            -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" \
            -var="AdminPassword=${{ secrets.VM_ADMIN_CREDENTIALS }}" \
            -var="HubEnabled=true" \
            -var="EnvName=hs-${{ github.event.inputs.environment }}"
          elif [ ${{ github.event.inputs.terraform_action }} = "destroy" ]; then
            terraform plan -destroy \
            -var="SubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" \
            -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" \
            -var="AdminPassword=${{ secrets.VM_ADMIN_CREDENTIALS }}" \
            -var="HubEnabled=false" \
            -var="EnvName=hs-${{ github.event.inputs.environment }}"
          else
              echo "Please input either an apply or destroy command (case sensitive)."
              exit 1
          fi
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.ARM_BACKEND_RESOURCE_GROUP_NAME }} 
          ARM_BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}
          ARM_CONTAINER_NAME: "sls-terraform-state-${{ github.event.inputs.environment }}"
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  App_Deployment:
    if: ${{ github.event.inputs.hub == 'true' }}
    name: Deployment - ${{ inputs.environment }} environment
    needs: App_Verification
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=${{ github.event.inputs.environment }}_SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_SECRET_NAME=${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
          echo "CONTAINER_SECRET_NAME=sls-terraform-state-${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "TFVARS_SECRET_NAME=${{ github.event.inputs.environment }}.auto.tfvars" >> $GITHUB_ENV
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Download TFVARS
        run: |
          az storage blob download \
            --file ./terraform/spoke/${{ env.TFVARS_SECRET_NAME }} \
            --container-name ${{ env.CONTAINER_SECRET_NAME }} \
            --account-name ${{ env.STORAGE_ACCOUNT_SECRET_NAME }} \
            --name ${{ env.TFVARS_SECRET_NAME }} \
            --auth-mode login \
            --no-progress > /dev/null
      - name: Terraform - Setup Backend and Apply
        run: |
          cd "terraform/spoke"
          cat >backend.tf <<EOL
          terraform {
            backend "azurerm" {
              subscription_id      = "$ARM_SUBSCRIPTION_ID"
              resource_group_name  = "$ARM_BACKEND_RESOURCE_GROUP_NAME"
              storage_account_name = "$ARM_BACKEND_STORAGE_ACCOUNT_NAME"
              container_name       = "$ARM_CONTAINER_NAME"
              key                  = "${{ github.event.inputs.environment }}.tfstate"
              client_id            = "$ARM_CLIENT_ID"
              client_secret        = "$ARM_CLIENT_SECRET"
              tenant_id            = "$ARM_TENANT_ID"
              use_azuread_auth     = true
            }
          }
          EOL
          terraform init
          if [ ${{ github.event.inputs.terraform_action }} = "apply" ]; then
            terraform ${{ github.event.inputs.terraform_action }} -auto-approve \
            -var="SubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" \
            -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" \
            -var="AdminPassword=${{ secrets.VM_ADMIN_CREDENTIALS }}" \
            -var="HubEnabled=true" \
            -var="EnvName=hs-${{ github.event.inputs.environment }}"
          elif [ ${{ github.event.inputs.terraform_action }} = "destroy" ]; then
            terraform ${{ github.event.inputs.terraform_action }} -auto-approve \
            -var="SubscriptionId=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" \
            -var="HubSubscriptionId=${{ secrets.HUB_SUBSCRIPTION_ID }}" \
            -var="AdminPassword=${{ secrets.VM_ADMIN_CREDENTIALS }}" \
            -var="HubEnabled=false" \
            -var="EnvName=hs-${{ github.event.inputs.environment }}"
          else
              echo "Please input either an apply or destroy command (case sensitive)."
              exit 1
          fi
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.ARM_BACKEND_RESOURCE_GROUP_NAME }} 
          ARM_BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}
          ARM_CONTAINER_NAME: "sls-terraform-state-${{ github.event.inputs.environment }}"
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

