# Trigger to run pipeline
on:
  # Triggers the workflow on push request events
  push:
    branches-ignore:
      - 'tags/*'

env:
  majorVersion: '24'
  minorVersion: '05'
  azEnvironments: 'hub,prod,dev'

# Name of build pipeline
name: build.beta.1

# Build pipeline jobs
jobs:
  Build_Information:
    name: Build Information
    runs-on: ubuntu-latest
    steps:
      - name: Collect Build Information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Version: ${{ github.run_number }}"

  Validate_Terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.Terraform_Version }}
      - name: Validate Terraform
        run: |
          IFS=',' read -ra ENV_LIST <<< "${azEnvironments}"
          for env in "${ENV_LIST[@]}"; do
            echo "##### Validating Terraform for $env #####"
            cd "terraform/$env"
            export ARM_BACKEND_CONTAINER_NAME="sls-terraform-state-$env"
            export ARM_BACKEND_KEY="$env.tfstate"
            terraform -v
            terraform init -backend=false
            terraform validate
          done

  Tag_Commit_with_Version:
    name: Tag Commit with Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SLS_EXTERNAL_SUBSCRIPTIONS_GITHUB }}
      - name: Push Version Tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag "${{env.majorVersion}}.${{env.minorVersion}}.${{github.run_number}}"
          git push --tags

