# Name of deploy pipeline
name: build.sls.packer

# General Notes
# -Passing lists directly through GitHub Actions Secrets or Variables causes deployment issues.


# Trigger to run pipeline
on:
  # This event allows you to trigger the workflow manually from the GitHub Actions tab in your repository.
  workflow_dispatch:
    inputs:
      architecture:
        description: 'Is a deployment of Packer needed for an image build?'
        required: true
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'
      environment:
        description: 'Please select a spoke name: dev, test, or prod'
        required: true
        type: choice
        options:
          - 'dev'
          - 'prod'
        default: 'dev'
      image-build:
        description: 'Is the image build for web, app, or data?'
        required: true
        type: choice
        options:
          - 'web'
          - 'app'
          - 'data'
        default: 'web'

# Deploy pipeline jobs
jobs:
  Input_Verification:
    name: User Input Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Make scripts executable
        run: chmod +x ./scripts/verify-architecture-selection.sh
      - name: Verify Deployment of Packer Architecture
        run: ./scripts/verify-architecture-selection.sh ${{ github.event.inputs.architecture }}
  Image_Build:
    name: Image Build - ${{ inputs.image-build }} tier in ${{ inputs.environment }} environment
    needs: Input_Verification
    runs-on: ubuntu-latest
    steps:
      - name: Set secret names
        id: set_secrets
        run: |
          echo "AZ_SP_SECRET_NAME=AZ_SP_${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID_SECRET_NAME=${{ github.event.inputs.environment }}_SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_SECRET_NAME=${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
          echo "CONTAINER_SECRET_NAME=sls-packer-${{ inputs.image-build }}-${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "PKVARS_SECRET_NAME=${{ inputs.image-build }}-${{ github.event.inputs.environment }}.auto.pkrvars.hcl" >> $GITHUB_ENV
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets[env.AZ_SP_SECRET_NAME] }}
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        id: setup
        with:
          version: ${{ env.PACKER_VERSION }}
      - name: Download PKVARS
        run: |
            az storage blob download \
            --file ./packer/${{ env.PKVARS_SECRET_NAME }} \
            --container-name ${{ env.CONTAINER_SECRET_NAME }} \
            --account-name ${{ env.STORAGE_ACCOUNT_SECRET_NAME }} \
            --name ${{ env.PKVARS_SECRET_NAME }} \
            --auth-mode login \
            --no-progress > /dev/null
      - name: Validate Packer
        run: |
          cd "packer"
          packer init .
          packer validate \
            -var "tenant_id=$ARM_TENANT_ID" \
            -var "subscription_id=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" \
            -var "client_id=$ARM_CLIENT_ID" \
            -var "client_secret=$ARM_CLIENT_SECRET" \
            -var-file="${{ github.event.inputs.image-build }}-${{ github.event.inputs.environment }}.auto.pkrvars.hcl" \
            build.pkr.hcl
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      - name: Build Packer
        run: |
          cd "packer"
          packer init .
          packer build \
            -var "tenant_id=$ARM_TENANT_ID" \
            -var "subscription_id=${{ secrets[env.SUBSCRIPTION_ID_SECRET_NAME] }}" \
            -var "client_id=$ARM_CLIENT_ID" \
            -var "client_secret=$ARM_CLIENT_SECRET" \
            -var-file="${{ github.event.inputs.image-build }}-${{ github.event.inputs.environment }}.auto.pkrvars.hcl" \
            build.pkr.hcl
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}