# Trigger to run pipeline
on:
  # Triggers the workflow on push request events
  push:
    branches-ignore:
      - 'tags/*'

env:
  majorVersion: '25'
  minorVersion: '03'

# Name of build pipeline
name: build.sls.lab

# Build pipeline jobs
jobs:
  Build_Information:
    name: Build Information
    runs-on: ubuntu-latest
    steps:
      - name: Collect Build Information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Version: ${{ github.run_number }}"

  Validate_Terraform:
    name: Validate Terraform
    needs: Build_Information
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Validate Terraform Hub
        run: |
          echo "##### Validating Terraform for Hub Code #####"
          cd "terraform/hub"
          terraform -v
          terraform init -backend=false
          terraform validate
      - name: Validate Terraform Application
        run: |
          echo "##### Validating Terraform for Application Code #####"
          cd "terraform/spoke"
          terraform -v
          terraform init -backend=false
          terraform validate
### Update folder above after testing.
  

  Tag_Commit_with_Version:
    name: Tag Commit with Version
    needs: Validate_Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SLS_EXTERNAL_SUBSCRIPTIONS_GITHUB }}
      - name: Push Version Tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          ### Set the ENDTAG based on the branch, it will be appended to the tag
          BRANCH_NAME=${{ github.ref }}
          BRANCH_NAME=${BRANCH_NAME#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME//_/-}
          ENDTAG=""
          if [[ "$BRANCH_NAME" == "main" ]]; then
            ENDTAG=""
          elif [[ "$BRANCH_NAME" =~ ^release/ ]]; then
            ENDTAG="-release"
          else
            ENDTAG="-$BRANCH_NAME"
          fi
        
          git tag "${{env.majorVersion}}.${{env.minorVersion}}.${{github.run_number}}${ENDTAG}"
          git push --tags

